### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/AirSensor2#1]
Items as they come up:

-----
_TODO:_

New in 2025

New 2023

- [ ] add `sensorToolkit_create???()` to create something from data in EPA sensorToolkit format. See: https://sensortoolkit.readthedocs.io/en/latest/index.html (6/01/23)
- [ ] update to **httr2** package (6/08/23)
- [ ] The countryCodes argument in pas_createNew() should be required and result in an error message if not supplied. (10/01/23)

----
_Items finished by 2025-03-25_

- [x] Add `countryCodes` argument to all Clarity_ functions so we can avoid expensive stateCode searches for non-US/CA/MX. (8/21/24)
- [x] Add support for Clarity calibrationCategory "Global PM2.5 v2.1".

----
_Items finished by 2025-03-22_

- [x] add `read_key` argument to `pat_createRaw()`, `pat_createHourly()` and all upstream functions (1/6/25)
- [x] allow `pas_createNew()` to specify which fields to download to save money (1/12/24)
- [x] parallel data download (9/15/23)

----
_Items finished by 2024-08-21_

- [x] Add support for Clarity `format = "USFS2"`. (8/20/24)
- [x] On May 1, 2024 the limits on requested data will increase. real-time: from 2 days to 30 days; hourly: from 14 days to 180 days. Update functions in `PurpleAir_API.`R to reflect this. (4/18/24)

----
_Items finished by 2023-09-22_

- [x] test all documented examples in vignettes and README.md. (9/13/23)

----
_Items finished by 2023-06-06_

- [x] update `Clarity_API.R` to handle the new nowcast QC flag (6/08)
